/**
 * Sample `DevLogView` data for `/system` and tests. Not recorded from GitHub or the Vinaya log —
 * this page's fixtures are always synthetic, because the real ones are this project's own
 * development history and change every time a ticket merges.
 */

import type { DevLogView } from "#/engine/dev-log-view.ts";

const MINUTE = 60_000;

export const normalDevLog: DevLogView = {
  milestone: { title: "Onchain Rewind v1: demo-ready", ticketsMerged: 3, ticketsTotal: 5 },
  headline: {
    medianTicketMs: 42 * MINUTE,
    secondRoundTickets: 1,
    reviewedTickets: 4,
    findings: { blocker: 1, major: 3, minor: 5, critical: 0, high: 1, medium: 2, low: 1 },
    findingsTotal: 13,
    typicalFiles: 4,
    typicalLines: 180,
    tokensIn: 3_200_000,
    tokensOut: 410_000,
  },
  timeSplit: { developerMs: 165 * MINUTE, reviewerMs: 58 * MINUTE, humanRulings: 1, recoveredTickets: 1 },
  guardrails: { checks: 6, runs: 214, stopped: 9 },
  workingNow: [{ issue: 25, title: "The share panel handles a wallet with no balance history", role: "reviewers" }],
  tickets: [
    {
      issue: 21,
      title: "The GitHub record of every task becomes a development record",
      status: "merged",
      pullRequest: {
        number: 49,
        url: "https://github.com/daniboomerang/onchain-rewind/pull/49",
        merged: true,
        filesChanged: 6,
        insertions: 410,
        deletions: 22,
        firstCommitAt: "2026-09-20T14:32:00Z",
      },
      humanRulingsCount: 1,
      codeVerdict: "approve",
      securityVerdict: "approve",
      buildMs: 58 * MINUTE,
      tokensIn: 980_000,
      tokensOut: 120_000,
      findings: { blocker: 1, major: 1, minor: 2, critical: 0, high: 0, medium: 0, low: 0 },
      roundCount: 1,
      rounds: [{ round: 1, outcome: "green" }],
      timeline: [
        {
          round: 1,
          repeat: false,
          developerMs: 22 * MINUTE,
          reviewerMs: 9 * MINUTE,
          outcome: "changes_requested",
          confidence: { value: 74, reason: "Two findings needed a second look." },
          filesChanged: 5,
          insertions: 300,
          deletions: 10,
          findings: { blocker: 1, major: 1, minor: 1, critical: 0, high: 0, medium: 0, low: 0 },
        },
        {
          round: 1,
          repeat: true,
          developerMs: 14 * MINUTE,
          reviewerMs: 6 * MINUTE,
          outcome: "green",
          confidence: { value: 91, reason: "Both findings from the ruling were fixed." },
          filesChanged: 6,
          insertions: 410,
          deletions: 22,
          findings: { blocker: 0, major: 0, minor: 1, critical: 0, high: 0, medium: 0, low: 0 },
        },
      ],
      running: false,
      recovered: false,
      paused: true,
    },
    {
      issue: 24,
      title: "The development record reads the Vinaya log correctly",
      status: "merged",
      pullRequest: {
        number: 45,
        url: "https://github.com/daniboomerang/onchain-rewind/pull/45",
        merged: true,
        filesChanged: 4,
        insertions: 180,
        deletions: 14,
      },
      humanRulingsCount: 0,
      codeVerdict: "approve",
      securityVerdict: "approve",
      buildMs: 31 * MINUTE,
      tokensIn: 720_000,
      tokensOut: 95_000,
      findings: { blocker: 0, major: 1, minor: 1, critical: 0, high: 0, medium: 0, low: 0 },
      roundCount: 1,
      rounds: [{ round: 1, outcome: "green" }],
      timeline: [
        {
          round: 1,
          repeat: false,
          developerMs: 24 * MINUTE,
          reviewerMs: 7 * MINUTE,
          outcome: "green",
          confidence: { value: 88, reason: "Fixtures cover every branch the fold takes." },
          filesChanged: 4,
          insertions: 180,
          deletions: 14,
          findings: { blocker: 0, major: 1, minor: 1, critical: 0, high: 0, medium: 0, low: 0 },
        },
      ],
      running: false,
      recovered: true,
      paused: false,
    },
    {
      issue: 20,
      title: "The Vinaya log's review-loop events become a round-by-round record",
      status: "merged",
      pullRequest: {
        number: 43,
        url: "https://github.com/daniboomerang/onchain-rewind/pull/43",
        merged: true,
        filesChanged: 3,
        insertions: 140,
        deletions: 8,
      },
      humanRulingsCount: 0,
      codeVerdict: "approve",
      securityVerdict: "pass",
      buildMs: 27 * MINUTE,
      tokensIn: 610_000,
      tokensOut: 88_000,
      findings: { blocker: 0, major: 1, minor: 1, critical: 0, high: 1, medium: 1, low: 1 },
      roundCount: 1,
      rounds: [{ round: 1, outcome: "green" }],
      timeline: [
        {
          round: 1,
          repeat: false,
          developerMs: 21 * MINUTE,
          reviewerMs: 8 * MINUTE,
          outcome: "green",
          confidence: { value: 82, reason: "One high finding from the security reviewer, fixed before merge." },
          filesChanged: 3,
          insertions: 140,
          deletions: 8,
          findings: { blocker: 0, major: 1, minor: 1, critical: 0, high: 1, medium: 1, low: 1 },
        },
      ],
      running: false,
      recovered: false,
      paused: false,
    },
    {
      issue: 25,
      title: "The share panel handles a wallet with no balance history",
      status: "in_review",
      pullRequest: {
        number: 51,
        url: "https://github.com/daniboomerang/onchain-rewind/pull/51",
        merged: false,
        filesChanged: 2,
        insertions: 60,
        deletions: 4,
      },
      humanRulingsCount: 0,
      codeVerdict: "approve",
      tokensIn: 340_000,
      tokensOut: 41_000,
      findings: { blocker: 0, major: 0, minor: 1, critical: 0, high: 0, medium: 0, low: 0 },
      roundCount: 1,
      rounds: [{ round: 1, outcome: undefined }],
      timeline: [
        {
          round: 1,
          repeat: false,
          developerMs: 18 * MINUTE,
          outcome: undefined,
          filesChanged: 2,
          insertions: 60,
          deletions: 4,
          findings: { blocker: 0, major: 0, minor: 1, critical: 0, high: 0, medium: 0, low: 0 },
        },
      ],
      running: true,
      recovered: false,
      paused: false,
    },
    {
      issue: 27,
      title: "A twelfth demo wallet replaces one that stopped producing a good story",
      status: "planned",
      humanRulingsCount: 0,
      tokensIn: 0,
      tokensOut: 0,
      findings: { blocker: 0, major: 0, minor: 0, critical: 0, high: 0, medium: 0, low: 0 },
      roundCount: 0,
      rounds: [],
      timeline: [],
      running: false,
      recovered: false,
      paused: false,
    },
  ],
};

export const emptyDevLog: DevLogView = {
  milestone: { title: "Onchain Rewind v1: demo-ready", ticketsMerged: 0, ticketsTotal: 0 },
  headline: {
    secondRoundTickets: 0,
    reviewedTickets: 0,
    findings: { blocker: 0, major: 0, minor: 0, critical: 0, high: 0, medium: 0, low: 0 },
    findingsTotal: 0,
    tokensIn: 0,
    tokensOut: 0,
  },
  workingNow: [],
  tickets: [],
};
